### ISSUE TITLE
Some Error,how to handle this

### ISSUE THREAD

**Issue by wawaup** [esappear/hexo-theme-clover#22]
```
ERROR ReferenceError: E:\Blog\themes\clover\layout\category.ejs:6
    4|   <% }) %>
    5| <% } else { %>
 >> 6|   <%
    7|     var CLOVER_OTHERS = '__CLOVER_OTHERS';
    8|     var totalPosts = _.orderBy(site.posts.data, function (post) {
    9|       return post.categories.data[0] ? post.categories.data[0].name : CLOVER_OTHERS;

_ is not defined
    at eval (E:\Blog\themes\clover\layout\category.ejs:25:22)
    at category (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:467:10)
    at resume_ (_stream_readable.js:981:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  path: 'E:\\Blog\\themes\\clover\\layout\\category.ejs'
}
ERROR ReferenceError: E:\Blog\themes\clover\layout\archive.ejs:2
    1| <section class="archive">
 >> 2|   <%
    3|   var groupPosts = _.groupBy(page.posts.data, function (post) {
    4|     return post.date.format('YYYY');
    5|   });

_ is not defined
    at eval (E:\Blog\themes\clover\layout\archive.ejs:11:20)
    at archive (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:467:10)
    at resume_ (_stream_readable.js:981:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  path: 'E:\\Blog\\themes\\clover\\layout\\archive.ejs'
}
ERROR ReferenceError: E:\Blog\themes\clover\layout\archive.ejs:2
    1| <section class="archive">
 >> 2|   <%
    3|   var groupPosts = _.groupBy(page.posts.data, function (post) {
    4|     return post.date.format('YYYY');
    5|   });

_ is not defined
    at eval (E:\Blog\themes\clover\layout\archive.ejs:11:20)
    at archive (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:467:10)
    at resume_ (_stream_readable.js:981:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  path: 'E:\\Blog\\themes\\clover\\layout\\archive.ejs'
}
ERROR ReferenceError: E:\Blog\themes\clover\layout\archive.ejs:2
    1| <section class="archive">
 >> 2|   <%
    3|   var groupPosts = _.groupBy(page.posts.data, function (post) {
    4|     return post.date.format('YYYY');
    5|   });

_ is not defined
    at eval (E:\Blog\themes\clover\layout\archive.ejs:11:20)
    at archive (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:467:10)
    at resume_ (_stream_readable.js:981:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  path: 'E:\\Blog\\themes\\clover\\layout\\archive.ejs'
}
ERROR ReferenceError: E:\Blog\themes\clover\layout\tag.ejs:3
    1| <% if (page.tag) { %>
    2|   <% page.posts.each(function(post){ %>
 >> 3|     <% var tag = _.find(theme.menu, function (item) {
    4|       return item.path === '/tags/' + page.tag;
    5|     }); %>
    6|     <%- partial('_partial/' + (theme.card_style.tag || 'article-card'), { post: post }) %>

_ is not defined
    at eval (E:\Blog\themes\clover\layout\tag.ejs:14:18)
    at _Query.forEach (E:\Blog\node_modules\warehouse\lib\query.js:36:7)
    at eval (E:\Blog\themes\clover\layout\tag.ejs:11:19)
    at tag (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:467:10)
    at resume_ (_stream_readable.js:981:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  path: 'E:\\Blog\\themes\\clover\\layout\\tag.ejs'
}
ERROR {
  err: ReferenceError: E:\Blog\themes\clover\layout\layout.ejs:12
      10| ">
      11|   <div id="container">
   >> 12|     <%- partial('_partial/nav') %>
      13|     <div id="main"><%- body %></div>
      14|     <%- partial('_partial/footer') %>
      15|   </div>

  E:\Blog\themes\clover\layout\_partial\nav.ejs:8
      6|     <div class="icons">
      7|       <% if (theme.social) { %>
   >> 8|         <% _.forEach(theme.social, function(value, key) { %>
      9|           <% if (value) { %>
      10|             <a href="<%= url_for(value) %>" target="_blank" class="nav-icn iconfont icon-<%= key.toLowerCase() %>"></a>
      11|           <% } %>

  _ is not defined
      at eval (E:\Blog\themes\clover\layout\_partial\nav.ejs:18:8)
      at nav (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:132:24)
      at _View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:59:25)
      at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
      at eval (E:\Blog\themes\clover\layout\layout.ejs:29:17)
      at layout (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiled (E:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
      at _View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
      at E:\Blog\node_modules\hexo\lib\theme\view.js:51:25
      at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (E:\Blog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (E:\Blog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\Blog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21) {
    path: 'E:\\Blog\\themes\\clover\\layout\\layout.ejs'
  }
} Render HTML failed: about/index.html
ERROR {
  err: ReferenceError: E:\Blog\themes\clover\layout\layout.ejs:12
      10| ">
      11|   <div id="container">
   >> 12|     <%- partial('_partial/nav') %>
      13|     <div id="main"><%- body %></div>
      14|     <%- partial('_partial/footer') %>
      15|   </div>

  E:\Blog\themes\clover\layout\_partial\nav.ejs:8
      6|     <div class="icons">
      7|       <% if (theme.social) { %>
   >> 8|         <% _.forEach(theme.social, function(value, key) { %>
      9|           <% if (value) { %>
      10|             <a href="<%= url_for(value) %>" target="_blank" class="nav-icn iconfont icon-<%= key.toLowerCase() %>"></a>
      11|           <% } %>

  _ is not defined
      at eval (E:\Blog\themes\clover\layout\_partial\nav.ejs:18:8)
      at nav (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:132:24)
      at _View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:59:25)
      at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
      at eval (E:\Blog\themes\clover\layout\layout.ejs:29:17)
      at layout (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiled (E:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
      at _View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
      at E:\Blog\node_modules\hexo\lib\theme\view.js:51:25
      at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (E:\Blog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (E:\Blog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\Blog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21) {
    path: 'E:\\Blog\\themes\\clover\\layout\\layout.ejs'
  }
} Render HTML failed: tags/index.html
ERROR {
  err: ReferenceError: E:\Blog\themes\clover\layout\layout.ejs:12
      10| ">
      11|   <div id="container">
   >> 12|     <%- partial('_partial/nav') %>
      13|     <div id="main"><%- body %></div>
      14|     <%- partial('_partial/footer') %>
      15|   </div>

  E:\Blog\themes\clover\layout\_partial\nav.ejs:8
      6|     <div class="icons">
      7|       <% if (theme.social) { %>
   >> 8|         <% _.forEach(theme.social, function(value, key) { %>
      9|           <% if (value) { %>
      10|             <a href="<%= url_for(value) %>" target="_blank" class="nav-icn iconfont icon-<%= key.toLowerCase() %>"></a>
      11|           <% } %>

  _ is not defined
      at eval (E:\Blog\themes\clover\layout\_partial\nav.ejs:18:8)
      at nav (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:132:24)
      at _View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:59:25)
      at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
      at eval (E:\Blog\themes\clover\layout\layout.ejs:29:17)
      at layout (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiled (E:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
      at _View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
      at E:\Blog\node_modules\hexo\lib\theme\view.js:51:25
      at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (E:\Blog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (E:\Blog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\Blog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21) {
    path: 'E:\\Blog\\themes\\clover\\layout\\layout.ejs'
  }
} Render HTML failed: 2020/09/23/CTF-intro/index.html
ERROR {
  err: ReferenceError: E:\Blog\themes\clover\layout\layout.ejs:12
      10| ">
      11|   <div id="container">
   >> 12|     <%- partial('_partial/nav') %>
      13|     <div id="main"><%- body %></div>
      14|     <%- partial('_partial/footer') %>
      15|   </div>

  E:\Blog\themes\clover\layout\_partial\nav.ejs:8
      6|     <div class="icons">
      7|       <% if (theme.social) { %>
   >> 8|         <% _.forEach(theme.social, function(value, key) { %>
      9|           <% if (value) { %>
      10|             <a href="<%= url_for(value) %>" target="_blank" class="nav-icn iconfont icon-<%= key.toLowerCase() %>"></a>
      11|           <% } %>

  _ is not defined
      at eval (E:\Blog\themes\clover\layout\_partial\nav.ejs:18:8)
      at nav (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:132:24)
      at _View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:59:25)
      at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
      at eval (E:\Blog\themes\clover\layout\layout.ejs:29:17)
      at layout (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiled (E:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
      at _View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
      at E:\Blog\node_modules\hexo\lib\theme\view.js:51:25
      at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (E:\Blog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (E:\Blog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\Blog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21) {
    path: 'E:\\Blog\\themes\\clover\\layout\\layout.ejs'
  }
} Render HTML failed: categories/Learning/index.html
ERROR {
  err: ReferenceError: E:\Blog\themes\clover\layout\layout.ejs:12
      10| ">
      11|   <div id="container">
   >> 12|     <%- partial('_partial/nav') %>
      13|     <div id="main"><%- body %></div>
      14|     <%- partial('_partial/footer') %>
      15|   </div>

  E:\Blog\themes\clover\layout\_partial\nav.ejs:8
      6|     <div class="icons">
      7|       <% if (theme.social) { %>
   >> 8|         <% _.forEach(theme.social, function(value, key) { %>
      9|           <% if (value) { %>
      10|             <a href="<%= url_for(value) %>" target="_blank" class="nav-icn iconfont icon-<%= key.toLowerCase() %>"></a>
      11|           <% } %>

  _ is not defined
      at eval (E:\Blog\themes\clover\layout\_partial\nav.ejs:18:8)
      at nav (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:132:24)
      at _View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:59:25)
      at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
      at eval (E:\Blog\themes\clover\layout\layout.ejs:29:17)
      at layout (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiled (E:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
      at _View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
      at E:\Blog\node_modules\hexo\lib\theme\view.js:51:25
      at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (E:\Blog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (E:\Blog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\Blog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21) {
    path: 'E:\\Blog\\themes\\clover\\layout\\layout.ejs'
  }
} Render HTML failed: index.html
ERROR ReferenceError: E:\Blog\themes\clover\layout\layout.ejs:12
    10| ">
    11|   <div id="container">
 >> 12|     <%- partial('_partial/nav') %>
    13|     <div id="main"><%- body %></div>
    14|     <%- partial('_partial/footer') %>
    15|   </div>

E:\Blog\themes\clover\layout\_partial\nav.ejs:8
    6|     <div class="icons">
    7|       <% if (theme.social) { %>
 >> 8|         <% _.forEach(theme.social, function(value, key) { %>
    9|           <% if (value) { %>
    10|             <a href="<%= url_for(value) %>" target="_blank" class="nav-icn iconfont icon-<%= key.toLowerCase() %>"></a>
    11|           <% } %>

_ is not defined
    at eval (E:\Blog\themes\clover\layout\_partial\nav.ejs:18:8)
    at nav (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\Blog\themes\clover\layout\layout.ejs:29:17)
    at layout (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\Blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\Blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21) {
  path: 'E:\\Blog\\themes\\clover\\layout\\layout.ejs'
}
ERROR ReferenceError: E:\Blog\themes\clover\layout\layout.ejs:12
    10| ">
    11|   <div id="container">
 >> 12|     <%- partial('_partial/nav') %>
    13|     <div id="main"><%- body %></div>
    14|     <%- partial('_partial/footer') %>
    15|   </div>

E:\Blog\themes\clover\layout\_partial\nav.ejs:8
    6|     <div class="icons">
    7|       <% if (theme.social) { %>
 >> 8|         <% _.forEach(theme.social, function(value, key) { %>
    9|           <% if (value) { %>
    10|             <a href="<%= url_for(value) %>" target="_blank" class="nav-icn iconfont icon-<%= key.toLowerCase() %>"></a>
    11|           <% } %>

_ is not defined
    at eval (E:\Blog\themes\clover\layout\_partial\nav.ejs:18:8)
    at nav (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\Blog\themes\clover\layout\layout.ejs:29:17)
    at layout (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\Blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\Blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21) {
  path: 'E:\\Blog\\themes\\clover\\layout\\layout.ejs'
}
ERROR ReferenceError: E:\Blog\themes\clover\layout\layout.ejs:12
    10| ">
    11|   <div id="container">
 >> 12|     <%- partial('_partial/nav') %>
    13|     <div id="main"><%- body %></div>
    14|     <%- partial('_partial/footer') %>
    15|   </div>

E:\Blog\themes\clover\layout\_partial\nav.ejs:8
    6|     <div class="icons">
    7|       <% if (theme.social) { %>
 >> 8|         <% _.forEach(theme.social, function(value, key) { %>
    9|           <% if (value) { %>
    10|             <a href="<%= url_for(value) %>" target="_blank" class="nav-icn iconfont icon-<%= key.toLowerCase() %>"></a>
    11|           <% } %>

_ is not defined
    at eval (E:\Blog\themes\clover\layout\_partial\nav.ejs:18:8)
    at nav (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\Blog\themes\clover\layout\layout.ejs:29:17)
    at layout (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\Blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\Blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21) {
  path: 'E:\\Blog\\themes\\clover\\layout\\layout.ejs'
}
ERROR ReferenceError: E:\Blog\themes\clover\layout\layout.ejs:12
    10| ">
    11|   <div id="container">
 >> 12|     <%- partial('_partial/nav') %>
    13|     <div id="main"><%- body %></div>
    14|     <%- partial('_partial/footer') %>
    15|   </div>

E:\Blog\themes\clover\layout\_partial\nav.ejs:8
    6|     <div class="icons">
    7|       <% if (theme.social) { %>
 >> 8|         <% _.forEach(theme.social, function(value, key) { %>
    9|           <% if (value) { %>
    10|             <a href="<%= url_for(value) %>" target="_blank" class="nav-icn iconfont icon-<%= key.toLowerCase() %>"></a>
    11|           <% } %>

_ is not defined
    at eval (E:\Blog\themes\clover\layout\_partial\nav.ejs:18:8)
    at nav (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\Blog\themes\clover\layout\layout.ejs:29:17)
    at layout (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\Blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\Blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21) {
  path: 'E:\\Blog\\themes\\clover\\layout\\layout.ejs'
}
ERROR ReferenceError: E:\Blog\themes\clover\layout\layout.ejs:12
    10| ">
    11|   <div id="container">
 >> 12|     <%- partial('_partial/nav') %>
    13|     <div id="main"><%- body %></div>
    14|     <%- partial('_partial/footer') %>
    15|   </div>

E:\Blog\themes\clover\layout\_partial\nav.ejs:8
    6|     <div class="icons">
    7|       <% if (theme.social) { %>
 >> 8|         <% _.forEach(theme.social, function(value, key) { %>
    9|           <% if (value) { %>
    10|             <a href="<%= url_for(value) %>" target="_blank" class="nav-icn iconfont icon-<%= key.toLowerCase() %>"></a>
    11|           <% } %>

_ is not defined
    at eval (E:\Blog\themes\clover\layout\_partial\nav.ejs:18:8)
    at nav (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (E:\Blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (E:\Blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (E:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\Blog\themes\clover\layout\layout.ejs:29:17)
    at layout (E:\Blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\Blog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\Blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\Blog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21) {
  path: 'E:\\Blog\\themes\\clover\\layout\\layout.ejs'
}
```

**Comment by doourdo** [comment]
I meet the same problem.lol

**Comment by lonbaw** [comment]
I meet the same problem !
how to resove it?

**Comment by yangstar23** [comment]
that is a problem i also meet

**Comment by yjgbg** [comment]
so am i

**Comment by lxtyin** [comment]
I meet it!
why "_ is not defined"?

**Comment by xzagit** [comment]
I meet the same problem

**Comment by evansuner** [comment]
The problem same as mine. called "_ is not defined", don't know how to solve it .

**Comment by zhangxiang-1222** [comment]
同样的错误

**Comment by AliceRayLu** [comment]
I met this too. And I changed "<%" into "<script>" tag, but this caused that the <a> tag inside is not rendered.

**Comment by Anning-Li** [comment]
same. Has anyone fixed it?

**Comment by image-builder-1837** [comment]
Hey, I met it too. It seems to be a problem about lodash, so I just replaced all lodash functions with native syntax. It works! I've created a PR, and so far you could download it at https://github.com/image-builder-1837/hexo-theme-clover

**Comment by imagebuilder1837** [comment]
Hey, I met it too. It seems to be a problem about lodash, so I just replaced all lodash functions with native syntax, and it works! I've created a PR, and this feature could be downloaded at https://github.com/image-builder-1837/hexo-theme-clover so far.
